[package]
name = "cargo-intra-converter"
version = "0.1.0"
authors = ["Alexis Bourget <alexis.bourget@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4"
ansi_term = "0.12"
